inteiros = int(input("Digite algo: "))
# int 7 -4 0  (numeros inteiros)
flutuante = float(input("Digite algo"))
# flot 9.2 -23 (numeros flutuantes)
bool = bool(input("true ou false?"))
# bool True ou False (So pode ser respondido com True ou False)
# jooj joao vitor(é usados para palavras)
palavras = str(input("digite seu nome"))
# jooj joao vitor(é usados para palavras)
